# Tomcat
server:
  port: 8081
# 服务名称
spring:
  application:
    name: study-gateway
  profiles:
#    环境配置
    active: dev
  cloud:
    nacos:
#        服务注册地址 配置中心地址
      server-addr: 127.0.0.1:8848
      discovery:
        username: root
        password: root
        service: ${spring.application.name}
        namespace: 8d12b20b-a97a-45d7-b34f-eb6f630b96bd
        enabled: true
      config:
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}
        encode: UTF-8
        enabled: true
        namespace: ${spring.cloud.nacos.discovery.namespace}
        file-extension: yml
        shared-configs: application-gateway-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

